/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pool_id": "ap-southeast-1_Mx3O0sUk2",
    "aws_user_pool_web_client_id": "3pqkoa0pqj54i1cm8kove9ohir",
    "aws_mandatory_sign_in": "enable",
    "aws_cloud_logic_custom": [
        {
            "name": "api-sls",
            "endpoint": "https://kgej3tyhk5.execute-api.ap-southeast-1.amazonaws.com/dev",
            "region": "ap-southeast-1"
        }
    ]    
};


export default awsmobile;
